### ISSUE TITLE
Fix the Category field in Add Tasks form

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/Simplii#12]
->In the Add Tasks page, the category field is a text field which accepts any value, but the when we're trying to filter out the tasks based on Category in the Dashboard, only 2 things are seen: 1)Intellectual 2)Physical. What it means is that, they're expecting only 2 fields. 
->Now, the core categories for categories are considered as Intellectual and Physical in our project which is what we need to show.

**How to fix?**
->Instead of a text field, create a dropdown instead and display only those 2 required values which the users can select from. 

![image](https://github.com/prateeksingamsetty/Simplii/assets/48323615/ccbe89e5-bc6d-4fa5-92c2-b3ca66f78c7f)

**Comment by laasya2704** [comment]
The issue has been fixed. Now the category box has a dropdown with two categories. I am closing the issue
<img width="1457" alt="Task Page" src="https://github.com/prateeksingamsetty/Simplii/assets/60955399/55866b6c-fdb2-4735-9d50-a7132019e7fd">
