### ISSUE TITLE
Undefined values in Update Tasks

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/Simplii#13]
->When the users update a task, undefined value is getting populated in Category field and also no values are getting populated in Start Date and End Date fields. We need to make sure to populate the values properly in order to give a clear idea to the users what they're going to update from.

**Observation**
->I think there's some issue in the code regarding the category field which needs to be taken care of and also there isn't any code related to Date field due to which they aren't getting populated.

![image](https://github.com/prateeksingamsetty/Simplii/assets/48323615/85f732c3-7f24-438f-838e-08b10c116c03)

**Comment by shiva1239** [comment]
Previously when ever we used to click edit task feature there was textbox which was being populated with undefined and start date and end date values were being populated with empty values. So i have updated this feature by fixing the text box to dropdown which have Physical and Intellectual Values and even i am populating this dates with original values. So this is fixed now.

<img width="1457" alt="Edit Page" src="https://github.com/prateeksingamsetty/Simplii/assets/61696599/baaffcba-54a0-4011-87df-70cc208eb6b7">
