### ISSUE TITLE
Implement forgot password feature

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/Simplii#14]
Previous team has left the forgot password feature under maintenance and haven't implemented it. This is an important feature to be covered as if the user forgets is password, there will be no way for him to check is tasks which will be a critical issue for him. 

**Previous Team**
![image](https://github.com/prateeksingamsetty/Simplii/assets/48323615/fb606cd9-a7f2-4539-a006-05f75b41b71d)

**Idea on how to build the feature**
->When the user clicks on the forgot password link, we need to ask him for his email details so that we can send a reset password link to his mail. Once the user clicks the link, it needs to redirect to our resetPassword page which has a new password field in there. Build on this idea to implement this feature.

**Comment by shiva1239** [comment]
For this feature we have integrated with Gmail, When ever the users clicks forget password we are sending them a mail with password reset link and user token. Using this link the user will set his new password and it gets updated in Mongodb.

<img width="1109" alt="Password Reset Link" src="https://github.com/prateeksingamsetty/Simplii/assets/61696599/a7766491-8098-4cc1-9ea0-e5aa939b3144">
