### ISSUE TITLE
Change in Status values

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/Simplii#16]
They're currently using 3 states for statuses:
1) In-Progress
2) Blocked
3) Done

It's quite unclear on what the Blocked state is used for:
Statuses that would make proper meaning are:
1)To-Do
2)In-Progress
3)Done

Need to make sure to change these statuses and we need to take care of all the references of these statuses(Ex: Dropdown in dashboard, etc)

**Comment by Jayanth0308** [comment]
I have fixed the issue. The values for status are now to-do, in-progress and done.
<img width="1457" alt="Task Page" src="https://github.com/prateeksingamsetty/Simplii/assets/145413068/3861d097-196c-44a9-aa86-2e1c960e1ab2">
