### ISSUE TITLE
Email on user registration

### ISSUE THREAD

**Issue by prateeksingamsetty** [prateeksingamsetty/Simplii#18]
When a user comes into the application and registers himself, send him out an email regarding some of the details of the application. The details could contain, what is the application regarding, what features can the user expect from this app and also how this application could help them in a daily way. 

**How to do**
->Need to use SMTP protocol here in order to send out the mail.
->Some app configurations need to be setup in the application like Sender mail id, hosts, port, etc.
->Use any of the python's email libraries to build this feature

**Comment by laasya2704** [comment]
Yes, this feature is now implemented using SMTP Protocol
![AccountCreatingEmail](https://github.com/prateeksingamsetty/Simplii/assets/60955399/79cc4d7d-7ebd-4715-b49b-9d306871912a)

**Comment by prateeksingamsetty** [comment]
Yes, that's the requirement. We can close the issue

**Comment by laasya2704** [comment]
Okay, I am closing the issue.
